apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: rauto-workload-887154-3e306675
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: workloads/helm3/nginx/nginx-9.4.2.tgz
      repository: rauto-git-repo
      revision: rauto-pipeline-test
      valuesPaths:
      - name: workloads/helm3/nginx/nginx-values-4-with-rauto-automation-ecr-registry.yaml
    options:
      description: rauto-test
      force: true
      maxHistory: 10
      noHooks: true
      setString:
      - service.type=NodePort
      timeout: 10m0s
    type: Helm
  namespace: rauto-namespace-887154
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: automation-cluster-boot-eks-3326
  version: rauto-workload-887154-3e306675-v1-202307122136520000
