apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    name: vijay
    surname: simha
  name: fleet-eks-cluster
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
    version: 2.0.0
  cloudCredentials: simha-aws
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      instanceTypes:
      - t3.xlarge
      maxSize: 4
      minSize: 1
      name: oct18-simha-new-ng
      ssh:
        allow: true
        publicKeyName: aws-abi-key
      version: "1.26"
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: fleet-eks-cluster
      region: us-west-2
      tags:
        email: vijay@rafay.co
        env: qa
      version: "1.26"
    network:
      cni:
        name: Calico-v3.24.5
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
