apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: rauto-namespace-55599
  project: defaultproject
spec:
  limitRange: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: automation-cluster-boot-eks-3362
  resourceQuotas: {}
