apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: rauto-namespace-493644
  project: defaultproject
spec:
  limitRange: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-k3d-48466
  resourceQuotas: {}
