apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: rauto-helm-repo
  project: defaultproject
spec:
  credentials:
    password: sealed://credentials.password
    username: admin
  endpoint: https://regression-charts.run.dev.rafay-edge.net/charts
  secret:
    name: file://artifacts/rauto-helm-repo/sealed-secret.yaml
  type: Helm
