apiVersion: apps.k8smgmt.io/v3
kind: Override
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: valuesFile
  name: rauto-cluster-override-workload
  project: defaultproject
spec:
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: automation-cluster-boot-eks-3326
  resource:
    selector:
      name: rauto-cluster-overides-test-donot-delete
    type: Workload
  type: Helm
  valuesPath:
    name: file://rauto-cluster-override-workload/rauto-cluster-override-workload.yaml
