apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: simha-eks
  project: defaultproject
spec:
  blueprintConfig:
    name: default
    version: 1.27.0
  cloudCredentials: simha-eks
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    metadata:
      name: simha-eks
      region: us-west-2
      tags:
        email: vijay@rafay.co
        env: qa
      version: "1.24"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      instancesDistribution:
        instanceTypes:
        - t3.xlarge
      maxSize: 2
      minSize: 1
      name: simha-eks-ng
      ssh:
        allow: true
        publicKeyName: aws-abi-key
      version: "1.24"
      volumeSize: 80
      volumeType: gp3
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
