apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: rauto-cluster-override-test-addon
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: workloads/helm3/nginx/nginx-9.4.2.tgz
      repository: rauto-git-repo
      revision: master
      valuesPaths:
      - name: workloads/helm3/nginx_automation/nginx-values-4-with-rauto-automation-ecr-registry.yaml
    type: Helm
  namespace: rauto-bootstrap-ns-358
  sharing: {}
  version: v1
