apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-cm-857668720
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: rauto_93760
  config:
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    metadata:
      name: rauto-cm-857668720
      region: us-east-1
      tags:
        email: automation@rafay.co
        env: automation
      version: "1.24"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: Ubuntu2004
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3a.xlarge
      maxSize: 2
      minSize: 2
      name: rauto-ng1-857668720
      overrideBootstrapCommand: null
      version: "1.24"
      volumeSize: 80
      volumeType: gp2
    - amiFamily: Ubuntu2004
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3a.xlarge
      maxSize: 2
      minSize: 2
      name: rauto-ng2-857668720
      overrideBootstrapCommand: null
      version: "1.24"
      volumeSize: 80
      volumeType: gp2
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: false
        publicAccess: true
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
