apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-gke-7635
  project: defaultproject
spec:
  blueprint:
    name: default-gke
    version: latest
  cloudCredentials: rauto-gke-cp-7635
  config:
    controlPlaneVersion: "1.23"
    gcpProject: qa-automation-371111
    location:
      config:
        region: us-central1
        zone: us-central1-a
      type: regional
    network:
      access:
        config:
          controlPlaneIPRange: 172.16.0.48/28
          disableSNAT: true
          enableAccessControlPlaneExternalIP: true
          enableAccessControlPlaneGlobal: true
        type: private
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: phani-vpc1
      subnetName: sub1-phani-vpc1
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      name: default-nodepool
      nodeVersion: "1.23"
      size: 1
    - autoScaling:
        maxNodes: 1
        minNodes: 1
      machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      name: second-nodepool
      nodeVersion: "1.23"
      size: 1
  type: gke
