apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rautocdktf-eks-835438
  project: defaultproject
spec:
  blueprintConfig:
    name: rautocdktf-blueprint-835438
    version: v1.0
  cloudCredentials: rautocdktf-cloudp-835438
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    metadata:
      name: rautocdktf-eks-835438
      region: us-east-1
      tags:
        email: automation@rafay.co
        env: automation
      version: "1.25"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: Bottlerocket
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      instanceType: t3a.xlarge
      maxSize: 2
      minSize: 1
      name: rauto-ng0
      privateNetworking: false
      version: "1.25"
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    - amiFamily: Bottlerocket
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      instanceType: t3a.xlarge
      maxSize: 2
      minSize: 1
      name: rauto-ng01
      privateNetworking: false
      version: "1.25"
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    vpc:
      autoAllocateIPv6: false
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: false
        publicAccess: true
      nat:
        gateway: Single
  type: aws-eks
