apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: simha-gke
  project: defaultproject
spec:
  blueprint:
    name: minimal
    version: latest
  config:
    controlPlaneVersion: "1.25"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: $__gcpproject
    location:
      config:
        zone: us-west1-c
      type: zonal
    network:
      access:
        config:
          controlPlaneIPRange: 172.16.0.0/28
          disableSNAT: true
          enableAccessControlPlaneExternalIP: true
          enableAccessControlPlaneGlobal: true
        type: private
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: default
      subnetName: default
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      name: default-nodepool
      nodeVersion: "1.25"
      size: 3
  type: gke
