apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: simha-repo
  project: defaultproject
spec:
  agents:
  - name: gitops-agent-1
  credentials:
    password: sealed://credentials.password
    username: vijay@rafay.co
  endpoint: https://github.com/Vijayrafay/demo-apps.git
  secret:
    name: file://artifacts/simha-repo/sealed-secret.yaml
  type: Git
